CC=g++
CFLAGS=-std=c++11 -Wall

all: 1 2 3

1: T5_Q1.cpp
	$(CC) $(CFLAGS) $^ -o $@

2: T5_Q2.cpp
	$(CC) $(CFLAGS) $^ -o $@

3: T5_Q3.cpp
	$(CC) $(CFLAGS) $^ -o $@

clean:
	rm 1.* 2.* 3.*